import { Container, Graphics } from 'pixi.js';
import type { GameContext, GameModule, InternalGameState } from '@runtime/types';
import { ARENA_CONFIG, BLESSINGS, ROOMS } from './config';
import type { Blessing, DamageNumber, LootItem, Particle, RunPhase } from './types';
import { Hero } from './entities/Hero';
import { Enemy } from './entities/Enemy';
import { BossMinotaur } from './entities/BossMinotaur';
import { Projectile } from './entities/Projectile';
import { DungeonArena } from './systems/DungeonArena';
import { CombatEngine } from './systems/CombatEngine';
import { TargetingSystem } from './systems/TargetingSystem';
import { SynergySystem } from './systems/SynergySystem';
import { HUDManager } from './systems/HUDManager';
import { CharacterSelectScreen } from './screens/CharacterSelectScreen';
import { PixelFont } from '../turbo-rider/render/PixelFont';

export default class DungeonBrawlGame implements GameModule {
  public state: InternalGameState = 'Initializing';
  private ctx!: GameContext; private root!: Container; private world = new Container(); private worldGraphics = new Graphics(); private uiGraphics = new Graphics();
  private heroes: Hero[] = []; private enemies: Enemy[] = []; private boss: BossMinotaur | null = null; private projectiles: Projectile[] = []; private loot: LootItem[] = []; private particles: Particle[] = []; private damageNumbers: DamageNumber[] = [];
  private readonly arena = new DungeonArena(); private readonly combat = new CombatEngine(); private readonly targeting = new TargetingSystem(); private readonly synergy = new SynergySystem(); private readonly hud = new HUDManager(); private readonly charSelect = new CharacterSelectScreen();
  private phase: RunPhase = 'select'; private roomIndex = 0; private waveIndex = 0; private phaseTimer = 0; private clock = 0; private id = 0; private completedBlessingRooms = new Set<number>(); private activeBlessings = new Set<Blessing['id']>(); private blessingChoices: Blessing[] = []; private blessingVotes = new Map<number, number>(); private blessingTimer = 0; private resultSent = false;

  public async init(context: GameContext): Promise<void> { this.ctx = context; this.root = new Container(); this.world.addChild(this.worldGraphics); this.root.addChild(this.world); this.root.addChild(this.uiGraphics); this.root.addChild(this.charSelect.container); this.ctx.renderer.stage.addChild(this.root); this.state = 'Ready'; }
  public start(): void { this.state = 'Playing'; }

  public update(dt: number): void {
    if (this.state !== 'Playing') return;
    this.clock += dt;
    if (this.phase === 'select') { this.updateSelection(dt); return; }
    if (this.phase === 'blessing') { this.updateBlessing(dt); this.render(); return; }
    if (this.phase === 'victory' || this.phase === 'defeat') { this.phaseTimer -= dt; this.render(); if (this.phaseTimer <= 0) this.finish(this.phase === 'victory'); return; }
    this.arena.update(dt); this.synergy.update(dt); this.combat.update(dt);
    if (this.phase === 'room-intro') { this.phaseTimer -= dt; if (this.phaseTimer <= 0) this.beginEncounter(); this.render(); return; }
    if (this.combat.hitStopTimer > 0) { this.updateEffects(dt); this.render(); return; }
    this.updateHeroes(dt); this.updateEnemies(dt); this.updateBoss(dt); this.updateProjectiles(dt); this.updateHazardsAndRevives(dt); this.updateLoot(dt); this.cleanupDeadEnemies(); this.updateEffects(dt);
    if (this.heroes.every(hero => !hero.isAlive)) { this.phase = 'defeat'; this.phaseTimer = 2.2; this.ctx.audio.playTone(120, 'sawtooth', .45); }
    else if (!this.enemies.length && !this.boss) this.advanceEncounter();
    this.render();
  }

  private updateSelection(dt: number): void { const count = Math.min(4, Math.max(2, this.ctx.players.length)); this.ctx.players.slice(0, count).forEach((player, index) => { const input = this.ctx.input.getPlayer(player.id); this.charSelect.updateInput(index + 1, input.isJustPressed('moveLeft'), input.isJustPressed('moveRight'), input.isJustPressed('action')); }); this.charSelect.render(count, dt); if (this.charSelect.isAllReady(count)) this.startRun(count); }
  private startRun(count: number): void { this.charSelect.container.visible = false; const positions = [{ x: 160, y: 160 }, { x: 320, y: 160 }, { x: 160, y: 205 }, { x: 320, y: 205 }]; this.heroes = this.ctx.players.slice(0, count).map((player, index) => new Hero(player.id, this.charSelect.selections[index + 1].classType, positions[index].x, positions[index].y)); this.roomIndex = 0; this.enterRoom(); this.ctx.audio.playTone(570, 'square', .25); }
  private enterRoom(): void { const room = ROOMS[this.roomIndex]; this.enemies = []; this.projectiles = []; this.loot = []; this.boss = null; this.waveIndex = 0; this.arena.setTheme(room.theme); this.phase = 'room-intro'; this.phaseTimer = 1.7; }
  private beginEncounter(): void { const room = ROOMS[this.roomIndex]; if (room.id === 'throne') { this.boss = new BossMinotaur(ARENA_CONFIG.width / 2, 80, this.heroes.length, this.ctx.modifiers.bossDifficulty ?? 1); } else this.spawnWave(room.waves[this.waveIndex]); this.phase = 'combat'; }
  private spawnWave(base: Enemy['type'][]): void { const extra = Math.max(0, this.heroes.length - 2); const list = [...base, ...Array.from({ length: extra }, (_, index) => base[index % base.length])]; list.forEach((type, index) => { const angle = (Math.PI * 2 * index) / list.length + this.ctx.random() * .32; const radius = 96 + this.ctx.random() * 65; const x = Math.max(45, Math.min(435, 240 + Math.cos(angle) * radius)); const y = Math.max(54, Math.min(215, 135 + Math.sin(angle) * radius)); const health = (this.ctx.modifiers.enemyHealthMultiplier ?? 1) * (1 + this.roomIndex * .13); this.enemies.push(new Enemy(`enemy-${this.id++}`, type as Exclude<Enemy['type'], 'minotaur_boss'>, x, y, health)); }); this.ctx.audio.playTone(240 + this.roomIndex * 35, 'square', .12); }

  private updateHeroes(dt: number): void { for (const hero of this.heroes) { const input = this.ctx.input.getPlayer(hero.id); if (input.isJustPressed('pause')) { this.ctx.events.emit('game:pause', undefined); return; } hero.update(dt, input.isActive('moveUp'), input.isActive('moveDown'), input.isActive('moveLeft'), input.isActive('moveRight')); if (!hero.isAlive) continue; const attackPressed = input.isJustPressed('action'); const skillPressed = input.isJustPressed('skill'); const ultimate = (attackPressed && input.isActive('skill')) || (skillPressed && input.isActive('action'));
      if (ultimate && hero.triggerUltimate()) { this.castUltimate(hero); this.ctx.audio.playTone(710, 'triangle', .32); continue; }
      if (attackPressed) { const target = this.targeting.findNearest(hero, this.enemies, this.boss, hero.config.attackRange + 28); if (hero.requestAttack(target.id, target.angle)) this.ctx.audio.playTone(hero.classType === 'barbarian' ? 180 : 310, 'sawtooth', .06, 'sfx', .07); }
      if (skillPressed && hero.triggerSpecial()) { if (this.activeBlessings.has('chrono')) hero.specialCooldownTimer *= .8; this.castSpecial(hero); this.ctx.audio.playTone(440, 'sine', .18); }
      const attack = hero.consumeAttack(); if (attack) this.applyAttack(hero, attack);
    } }
  private applyAttack(hero: Hero, attack: import('./types').AttackEvent): void { const result = this.combat.resolveAttack(hero, attack, this.enemies, this.boss); this.damageNumbers.push(...result.damageNumbers); this.particles.push(...result.particles); if (result.hit && attack.comboStep === 2) { this.synergy.triggerSynergy('FINISHER', attack.x + Math.cos(attack.angle) * 22, attack.y + Math.sin(attack.angle) * 22, hero.config.secondaryColor); if (this.activeBlessings.has('storm')) { const target = this.targeting.findNearest(hero, this.enemies.filter(enemy => enemy.id !== attack.targetId), this.boss, 95); const chained = this.enemies.find(enemy => enemy.id === target.id); if (chained) { const value = chained.takeDamage(Math.round(attack.damage * .55)); this.damageNumbers.push({ x: chained.x, y: chained.y - 22, value, color: 0x6ff7ff, lifetime: .7, vy: -22 }); this.synergy.triggerSynergy('STORM', chained.x, chained.y, 0x6ff7ff); } } } }
  private castSpecial(hero: Hero): void { const nearest = this.targeting.findNearest(hero, this.enemies, this.boss, hero.classType === 'wizard' ? 150 : 92); if (hero.classType === 'knight') { this.synergy.triggerSynergy('SHIELD WALL', hero.x, hero.y, 0x6ff7ff); this.enemies.forEach(enemy => { if (Math.hypot(enemy.x - hero.x, enemy.y - hero.y) < 86) { enemy.targetHeroId = hero.id; enemy.stunTimer = .35; } }); }
    else if (hero.classType === 'wizard') { this.enemies.forEach(enemy => { if (Math.hypot(enemy.x - hero.x, enemy.y - hero.y) < 82) { enemy.isFrozen = true; enemy.freezeTimer = 2.3; } }); if (nearest.id) { const speed = 230; this.projectiles.push(new Projectile(`bolt-${this.id++}`, hero.id, hero.x, hero.y - 8, Math.cos(nearest.angle) * speed, Math.sin(nearest.angle) * speed, 32, 'arcane_bolt', { homing: true })); } this.synergy.triggerSynergy('FROST NOVA', hero.x, hero.y, 0x6ff7ff); }
    else if (hero.classType === 'rogue') { if (nearest.id) { hero.x = Math.max(28, Math.min(452, nearest.x - Math.cos(nearest.angle) * 17)); hero.y = Math.max(34, Math.min(232, nearest.y - Math.sin(nearest.angle) * 17)); const enemy = this.enemies.find(item => item.id === nearest.id); if (enemy) { const damage = enemy.takeDamage(44); enemy.isExposed = true; enemy.exposedTimer = 4; this.damageNumbers.push({ x: enemy.x, y: enemy.y - 22, value: damage, color: 0x7de38a, lifetime: .7, vy: -25 }); } } this.synergy.triggerSynergy('SHADOW DASH', hero.x, hero.y, 0x7de38a); }
    else { this.enemies.forEach(enemy => { const d = Math.hypot(enemy.x - hero.x, enemy.y - hero.y); if (d < 76) { enemy.takeDamage(38, (enemy.x - hero.x) / Math.max(1, d) * 110, (enemy.y - hero.y) / Math.max(1, d) * 110); enemy.stunTimer = 1.05; } }); this.synergy.triggerSynergy('GROUND SLAM', hero.x, hero.y, 0xff884a); }
    if (this.activeBlessings.has('ember')) this.projectiles.push(new Projectile(`ember-${this.id++}`, hero.id, hero.x, hero.y, 0, 0, 14, 'lava_wave', { splashRadius: 38 })); }
  private castUltimate(hero: Hero): void { const cluster = this.targeting.findCluster(hero, this.enemies, this.boss, 180); if (hero.classType === 'knight') { this.enemies.forEach(enemy => { if (Math.hypot(enemy.x - hero.x, enemy.y - hero.y) < 86) enemy.takeDamage(82); }); if (this.boss && Math.hypot(this.boss.x - hero.x, this.boss.y - hero.y) < 96) this.boss.takeDamage(74); this.synergy.triggerSynergy('WHIRLING BLADE', hero.x, hero.y, 0xf2c14e); }
    else if (hero.classType === 'wizard') { for (let i = 0; i < 5; i++) { const a = i * 1.256; this.projectiles.push(new Projectile(`meteor-${this.id++}`, hero.id, cluster.x + Math.cos(a) * (i % 2 ? 18 : 4), cluster.y + Math.sin(a) * (i % 2 ? 18 : 4), 0, 0, 62, 'meteor', { splashRadius: 48 })); } this.synergy.triggerSynergy('METEOR STORM', cluster.x, cluster.y, 0xf2c14e); }
    else if (hero.classType === 'rogue') { for (let i = 0; i < 8; i++) { const angle = i * Math.PI / 4; this.projectiles.push(new Projectile(`rain-${this.id++}`, hero.id, cluster.x + Math.cos(angle) * 72, cluster.y + Math.sin(angle) * 72, -Math.cos(angle) * 150, -Math.sin(angle) * 150, 35, 'shadow_blade', { splashRadius: 18 })); } this.synergy.triggerSynergy('CROSSBOW RAIN', cluster.x, cluster.y, 0x7de38a); }
    else this.synergy.triggerSynergy('BERSERKER RAGE', hero.x, hero.y, 0xff526b);
  }

  private updateEnemies(dt: number): void { for (const enemy of this.enemies) { const result = enemy.update(dt, this.heroes, this.enemies); if (result.shoot && result.target) { const angle = Math.atan2(result.target.y - enemy.y, result.target.x - enemy.x); this.projectiles.push(new Projectile(`arrow-${this.id++}`, 0, enemy.x, enemy.y - 7, Math.cos(angle) * 176, Math.sin(angle) * 176, enemy.damage, 'arrow')); } if (result.fireZone && result.target) this.projectiles.push(new Projectile(`fire-${this.id++}`, 0, result.target.x, result.target.y, 0, 0, enemy.damage, 'fire_orb', { splashRadius: 30 })); for (const hero of this.heroes) if (hero.isAlive && Math.hypot(hero.x - enemy.x, hero.y - enemy.y) < enemy.radius + 10 && enemy.attackCooldown <= 0) { const dealt = hero.takeDamage(enemy.damage); enemy.attackCooldown = .78; if (dealt) this.damageNumbers.push({ x: hero.x, y: hero.y - 23, value: dealt, color: 0xff526b, lifetime: .7, vy: -22 }); } } }
  private updateBoss(dt: number): void { if (!this.boss) return; const result = this.boss.update(dt, this.heroes); if (result.shockwave) { this.projectiles.push(new Projectile(`quake-${this.id++}`, 0, this.boss.x, this.boss.y, 0, 0, 28, 'lava_wave', { splashRadius: 84 })); this.synergy.triggerSynergy('EARTHSHAKER', this.boss.x, this.boss.y, 0xff526b); if (result.summon) for (let i = 0; i < 2; i++) this.enemies.push(new Enemy(`summon-${this.id++}`, i ? 'imp' : 'wraith', this.boss.x + (i ? 36 : -36), this.boss.y + 30, 1 + this.roomIndex * .12)); } if (result.chargeHit) for (const hero of this.heroes) if (hero.isAlive && Math.hypot(hero.x - this.boss.x, hero.y - this.boss.y) < 34) hero.takeDamage(30); if (this.boss.hp <= 0) { this.boss = null; this.ctx.audio.playTone(820, 'triangle', .45); } }
  private updateProjectiles(dt: number): void { for (let i = this.projectiles.length - 1; i >= 0; i--) { const projectile = this.projectiles[i]; if (!projectile.update(dt, this.enemies)) { this.projectiles.splice(i, 1); continue; } const targets = projectile.ownerId > 0 ? this.enemies : []; let hit = false; if (projectile.ownerId > 0) { for (const enemy of targets) { if (enemy.hp > 0 && Math.hypot(enemy.x - projectile.x, enemy.y - projectile.y) < enemy.radius + projectile.radius) { enemy.takeDamage(projectile.damage); this.damageNumbers.push({ x: enemy.x, y: enemy.y - 18, value: projectile.damage, color: projectile.color, lifetime: .7, vy: -20 }); hit = true; break; } } if (!hit && this.boss && Math.hypot(this.boss.x - projectile.x, this.boss.y - projectile.y) < this.boss.radius + projectile.radius) { this.boss.takeDamage(projectile.damage); hit = true; } } else { for (const hero of this.heroes) if (hero.isAlive && Math.hypot(hero.x - projectile.x, hero.y - projectile.y) < 12 + projectile.radius) { hero.takeDamage(projectile.damage); hit = true; break; } } if (hit || projectile.splashRadius) { if (projectile.splashRadius) { if (projectile.ownerId > 0) this.enemies.forEach(enemy => { if (Math.hypot(enemy.x - projectile.x, enemy.y - projectile.y) < projectile.splashRadius!) enemy.takeDamage(projectile.damage); }); else this.heroes.forEach(hero => { if (hero.isAlive && Math.hypot(hero.x - projectile.x, hero.y - projectile.y) < projectile.splashRadius!) hero.takeDamage(projectile.damage); }); this.synergy.triggerSynergy('IMPACT', projectile.x, projectile.y, projectile.color); } this.projectiles.splice(i, 1); } } }
  private updateHazardsAndRevives(dt: number): void { for (const hero of this.heroes) { if (hero.isAlive) { const hurt = this.arena.hurtAt(hero.x, hero.y); if (hurt) hero.takeDamage(hurt); } else if (hero.isDowned) { const helper = this.heroes.find(other => other.isAlive && Math.hypot(other.x - hero.x, other.y - hero.y) < 38); if (helper) { hero.reviveProgress += dt; if (hero.reviveProgress >= 2) { hero.revive(); helper.revives++; helper.score += 75; helper.ultimate = Math.min(100, helper.ultimate + 25); if (this.activeBlessings.has('iron')) { hero.isInvulnerable = true; hero.invulnerableTimer = 3; } this.synergy.triggerSynergy('REVIVED', hero.x, hero.y, 0x7de38a); } } else hero.reviveProgress = Math.max(0, hero.reviveProgress - dt * .6); } } }
  private updateLoot(dt: number): void { for (let i = this.loot.length - 1; i >= 0; i--) { const item = this.loot[i]; item.lifetime -= dt; if (item.lifetime <= 0) { this.loot.splice(i, 1); continue; } const hero = this.heroes.find(candidate => candidate.isAlive && Math.hypot(candidate.x - item.x, candidate.y - item.y) < 14); if (!hero) continue; if (item.type === 'health_potion') this.heroes.forEach(member => member.hp = Math.min(member.maxHp, member.hp + item.value)); else if (item.type === 'mana_gem') hero.mana = Math.min(hero.maxMana, hero.mana + item.value); else hero.ultimate = Math.min(100, hero.ultimate + item.value); this.loot.splice(i, 1); this.ctx.audio.playTone(650, 'sine', .1); } }
  private cleanupDeadEnemies(): void { for (let i = this.enemies.length - 1; i >= 0; i--) { const enemy = this.enemies[i]; if (enemy.hp > 0) continue; const killer = this.heroes.reduce((best, hero) => hero.targetId === enemy.id ? hero : best, this.heroes[0]); killer.kills++; killer.score += enemy.type === 'brute' ? 80 : 30; killer.ultimate = Math.min(100, killer.ultimate + 9); if (enemy.type === 'slime') { this.enemies.push(new Enemy(`mini-${this.id++}`, 'mini_slime', enemy.x - 7, enemy.y, 1 + this.roomIndex * .1), new Enemy(`mini-${this.id++}`, 'mini_slime', enemy.x + 7, enemy.y, 1 + this.roomIndex * .1)); } const dropChance = this.activeBlessings.has('fortune') ? .58 : .35; if (this.ctx.random() < dropChance) { const roll = this.ctx.random(); this.loot.push({ id: `loot-${this.id++}`, type: roll < .38 ? 'health_potion' : roll < .75 ? 'mana_gem' : 'soul_orb', x: enemy.x, y: enemy.y, value: roll < .38 ? 12 : roll < .75 ? 22 : 14, lifetime: 10 }); } if (this.activeBlessings.has('blood')) this.heroes.forEach(hero => hero.hp = Math.min(hero.maxHp, hero.hp + 4)); this.particles.push(...Array.from({ length: 10 }, (_, index) => ({ x: enemy.x, y: enemy.y, vx: Math.cos(index * .63) * (32 + index * 3), vy: Math.sin(index * .63) * (32 + index * 3), life: .5, maxLife: .5, color: enemy.color, size: 2 }))); this.enemies.splice(i, 1); } }
  private updateEffects(dt: number): void { for (let i = this.particles.length - 1; i >= 0; i--) { const p = this.particles[i]; p.x += p.vx * dt; p.y += p.vy * dt; p.vy += 35 * dt; p.life -= dt; if (p.life <= 0) this.particles.splice(i, 1); } for (let i = this.damageNumbers.length - 1; i >= 0; i--) { const n = this.damageNumbers[i]; n.y += n.vy * dt; n.lifetime -= dt; if (n.lifetime <= 0) this.damageNumbers.splice(i, 1); } }
  private advanceEncounter(): void { const room = ROOMS[this.roomIndex]; if (room.id === 'throne') { this.phase = 'victory'; this.phaseTimer = 2.5; return; } if (this.waveIndex + 1 < room.waves.length) { this.waveIndex++; this.spawnWave(room.waves[this.waveIndex]); return; } if (room.hasBlessingAfter && !this.completedBlessingRooms.has(this.roomIndex)) { this.completedBlessingRooms.add(this.roomIndex); this.beginBlessing(); return; } this.roomIndex++; this.enterRoom(); }
  private beginBlessing(): void { const pool = [...BLESSINGS]; const choices: Blessing[] = []; while (choices.length < 3) choices.push(pool.splice(Math.floor(this.ctx.random() * pool.length), 1)[0]); this.blessingChoices = choices; this.blessingVotes.clear(); this.blessingTimer = 8; this.phase = 'blessing'; }
  private updateBlessing(dt: number): void { this.blessingTimer -= dt; for (const hero of this.heroes) { const input = this.ctx.input.getPlayer(hero.id); const current = this.blessingVotes.get(hero.id) ?? 0; if (input.isJustPressed('moveLeft')) this.blessingVotes.set(hero.id, (current + 2) % 3); if (input.isJustPressed('moveRight')) this.blessingVotes.set(hero.id, (current + 1) % 3); if (input.isJustPressed('action')) this.blessingVotes.set(hero.id, this.blessingVotes.get(hero.id) ?? 0); } if (this.blessingVotes.size === this.heroes.length || this.blessingTimer <= 0) { const counts = [0, 0, 0]; this.blessingVotes.forEach(vote => counts[vote]++); const highest = Math.max(...counts); const tied = counts.map((count, index) => count === highest ? index : -1).filter(index => index >= 0); const selected = tied[Math.floor(this.ctx.random() * tied.length)]; this.activeBlessings.add(this.blessingChoices[selected].id); this.roomIndex++; this.enterRoom(); this.ctx.audio.playTone(760, 'triangle', .26); } }
  private render(): void { this.worldGraphics.clear(); this.arena.render(this.worldGraphics); for (const item of this.loot) { const color = item.type === 'health_potion' ? 0xff526b : item.type === 'mana_gem' ? 0x6ff7ff : 0xf2c14e; this.worldGraphics.circle(Math.round(item.x), Math.round(item.y), 5).fill({ color }); this.worldGraphics.circle(Math.round(item.x), Math.round(item.y), 8).stroke({ color, width: 1, alpha: .5 }); } this.projectiles.forEach(projectile => projectile.render(this.worldGraphics)); this.enemies.forEach(enemy => enemy.render(this.worldGraphics, this.clock)); if (this.boss) this.boss.render(this.worldGraphics, this.clock); this.heroes.forEach(hero => hero.render(this.worldGraphics, this.clock)); this.synergy.render(this.worldGraphics); this.particles.forEach(p => this.worldGraphics.rect(Math.round(p.x), Math.round(p.y), p.size, p.size).fill({ color: p.color, alpha: p.life / p.maxLife })); this.damageNumbers.forEach(n => PixelFont.drawText(this.worldGraphics, `${n.value}`, Math.round(n.x), Math.round(n.y), n.color, 1, Math.max(0, n.lifetime / .7))); const shake = this.combat.cameraShake > 0 ? Math.ceil(Math.sin(this.clock * 170) * 2) : 0; this.world.x = shake; this.world.y = -shake;
    this.uiGraphics.clear(); const room = ROOMS[this.roomIndex]; this.hud.render(this.uiGraphics, this.heroes, room?.title ?? 'DUNGEON', this.enemies.length + (this.boss ? 1 : 0), this.phase, this.boss ? { hp: this.boss.hp, maxHp: this.boss.maxHp, phase: this.boss.phase } : undefined, this.phase === 'blessing' ? { choices: this.blessingChoices, votes: this.blessingVotes, time: this.blessingTimer } : undefined); if (this.phase === 'victory' || this.phase === 'defeat') { this.uiGraphics.rect(0, 0, 480, 270).fill({ color: 0x08040e, alpha: .76 }); PixelFont.drawText(this.uiGraphics, this.phase === 'victory' ? 'THE HORNED KING FALLS' : 'THE DUNGEON CLAIMS YOU', 126, 110, this.phase === 'victory' ? 0xf2c14e : 0xff526b, 2); PixelFont.drawText(this.uiGraphics, this.phase === 'victory' ? 'TEAM VICTORY' : 'TEAM WIPED', 187, 143, 0xeaf6ff, 1); } }
  private finish(victory: boolean): void { if (this.resultSent) return; this.resultSent = true; this.state = 'Finished'; const standings = [...this.heroes].sort((a, b) => b.score - a.score).map(hero => ({ playerId: hero.id, score: hero.score })); this.ctx.events.emit('game:over', { winnerId: victory ? (standings[0]?.playerId ?? 1) : 0, isTeamLoss: !victory, isTeamVictory: victory, standings }); }
  public pause(): void { this.state = 'Paused'; } public resume(): void { this.state = 'Playing'; } public destroy(): void { this.state = 'Destroyed'; this.charSelect.destroy(); this.worldGraphics.destroy(); this.uiGraphics.destroy(); this.root.destroy({ children: true }); }
}
