import { Container, Graphics } from 'pixi.js';
import type { HeroClassType } from '../types';
import { HERO_CONFIGS, ARENA_CONFIG } from '../config';
import { PixelFont } from '../../turbo-rider/render/PixelFont';

export class CharacterSelectScreen {
  public container = new Container(); private g = new Graphics(); public selections: Record<number, { classType: HeroClassType; isReady: boolean }> = { 1: { classType: 'knight', isReady: false }, 2: { classType: 'wizard', isReady: false }, 3: { classType: 'rogue', isReady: false }, 4: { classType: 'barbarian', isReady: false } }; private readonly order: HeroClassType[] = ['knight', 'wizard', 'rogue', 'barbarian']; private clock = 0;
  constructor() { this.container.addChild(this.g); }
  public updateInput(id: number, left: boolean, right: boolean, action: boolean): void { const selection = this.selections[id]; if (!selection) return; if ((left || right) && !selection.isReady) { const current = this.order.indexOf(selection.classType); selection.classType = this.order[(current + (right ? 1 : -1) + this.order.length) % this.order.length]; } if (action) selection.isReady = !selection.isReady; }
  public isAllReady(count: number): boolean { return Array.from({ length: count }, (_, index) => this.selections[index + 1].isReady).every(Boolean); }
  public render(count: number, dt = 1 / 60): void { this.clock += dt; const { width: w, height: h } = ARENA_CONFIG; this.g.clear(); this.g.rect(0, 0, w, h).fill({ color: 0x090611 }); for (let x = 0; x < w; x += 24) for (let y = 0; y < h; y += 24) if ((x + y) % 48 === 0) this.g.rect(x, y, 1, 1).fill({ color: 0x6ff7ff, alpha: .25 }); PixelFont.drawText(this.g, 'DUNGEON BRAWL', 160, 10, 0xf2c14e, 2); PixelFont.drawText(this.g, 'CHOOSE YOUR CHAMPION', 154, 29, 0x6ff7ff, 1); const twoRows = count > 2; const cardW = twoRows ? 212 : 205; const cardH = twoRows ? 91 : 164; for (let i = 0; i < count; i++) { const id = i + 1; const sel = this.selections[id]; const cfg = HERO_CONFIGS[sel.classType]; const col = twoRows ? i % 2 : i; const row = twoRows ? Math.floor(i / 2) : 0; const x = twoRows ? 26 + col * 216 : 32 + col * 220; const y = twoRows ? 51 + row * 98 : 52; const border = sel.isReady ? 0x7de38a : cfg.primaryColor; this.g.rect(x, y, cardW, cardH).fill({ color: 0x171025 }); this.g.rect(x, y, cardW, cardH).stroke({ color: border, width: 2 }); this.g.rect(x + 10, y + 25, 45, cardH - 35).fill({ color: cfg.primaryColor, alpha: .32 }); this.g.circle(x + 32, y + 49, 17 + Math.sin(this.clock * 5 + id) * 1).stroke({ color: cfg.secondaryColor, width: 3 }); this.g.rect(x + 25, y + 39, 14, 22).fill({ color: cfg.primaryColor }); this.g.rect(x + 27, y + 30, 10, 9).fill({ color: cfg.secondaryColor }); PixelFont.drawText(this.g, `P${id} ${cfg.name}`, x + 65, y + 10, cfg.primaryColor, 1); PixelFont.drawText(this.g, cfg.role, x + 65, y + 25, 0xa48ba8, 1); PixelFont.drawText(this.g, `ATK ${cfg.attackPower} HP ${cfg.maxHp}`, x + 65, y + 39, 0xeaf6ff, 1); PixelFont.drawText(this.g, cfg.specialSkillName, x + 65, y + 54, cfg.secondaryColor, 1); PixelFont.drawText(this.g, cfg.ultimateSkillName, x + 65, y + 68, 0xf2c14e, 1); PixelFont.drawText(this.g, sel.isReady ? 'READY' : '< > CHOOSE  ATTACK READY', x + 8, y + cardH - 13, sel.isReady ? 0x7de38a : 0xeaf6ff, 1); }
    PixelFont.drawText(this.g, 'SMART TARGETING ON  SKILL IS SPECIAL  HOLD ONE + PRESS OTHER FOR ULT', 52, 250, 0xa48ba8, 1); }
  public destroy(): void { this.g.destroy(); this.container.destroy(); }
}
