import type { GameManifest } from '@runtime/types';

const manifest: GameManifest = {
  id: 'rento',
  title: 'RENTO',
  description:
    'Build a property empire, master a shifting economy, trade with rivals, and win by net worth or classic bankruptcy.',
  version: '1.0.0',
  author: 'PartyPlay Studio',
  category: 'Strategy',
  thumbnail: '',
  tags: ['Board Game', 'Strategy', 'Economy', 'Trading', 'Local Multiplayer'],
  difficulty: 'Medium',
  minPlayers: 1,
  maxPlayers: 4,
  estimatedRoundTime: '30-45 min',
  logicalWidth: 960,
  logicalHeight: 540,
  displayScale: 'fit',
  capabilities: {
    supportsPause: true,
    supportsRestart: true,
    supportsModifiers: true,
    supportsSeed: true,
    supportsGamepad: true,
    supportsTouch: true,
  },
  defaultControls: [
    {
      playerId: 1,
      deviceId: 'keyboard-main',
      bindings: {
        moveUp: ['KeyW'],
        moveDown: ['KeyS'],
        moveLeft: ['KeyA'],
        moveRight: ['KeyD'],
        action: ['Space', 'KeyF'],
        alternate: ['KeyE'],
        pause: ['Escape'],
      },
    },
    {
      playerId: 2,
      deviceId: 'keyboard-main',
      bindings: {
        moveUp: ['ArrowUp'],
        moveDown: ['ArrowDown'],
        moveLeft: ['ArrowLeft'],
        moveRight: ['ArrowRight'],
        action: ['Enter', 'Slash'],
        alternate: ['Period'],
        pause: ['Escape'],
      },
    },
    {
      playerId: 3,
      deviceId: 'keyboard-main',
      bindings: {
        moveUp: ['KeyI'],
        moveDown: ['KeyK'],
        moveLeft: ['KeyJ'],
        moveRight: ['KeyL'],
        action: ['KeyU'],
        alternate: ['KeyO'],
        pause: ['Escape'],
      },
    },
    {
      playerId: 4,
      deviceId: 'keyboard-main',
      bindings: {
        moveUp: ['Numpad8'],
        moveDown: ['Numpad5'],
        moveLeft: ['Numpad4'],
        moveRight: ['Numpad6'],
        action: ['Numpad0'],
        alternate: ['NumpadEnter'],
        pause: ['Escape'],
      },
    },
  ],
  defaultModifiers: {
    winMode: 'netWorth',
    roundLimit: 30,
    turnTimerSeconds: 45,
    economyVolatility: 'dynamic',
    animationSpeed: 1,
    aiDifficulty: 'normal',
  },
  setup: {
    players: {
      supportsBots: true,
      defaultPlayerType: 'human',
      aiDifficultyOptions: ['easy', 'normal', 'hard'],
      defaultAIDifficulty: 'normal',
    },
    options: [
      {
        key: 'winMode',
        type: 'select',
        label: 'VICTORY CONDITION',
        description: 'Choose a strategic turn limit or classic last-player-standing rules.',
        options: [
          { value: 'netWorth', label: 'HIGHEST NET WORTH' },
          { value: 'bankruptcy', label: 'CLASSIC BANKRUPTCY' },
        ],
        defaultValue: 'netWorth',
      },
      {
        key: 'roundLimit',
        type: 'select',
        label: 'MATCH LENGTH',
        options: [
          { value: 20, label: 'QUICK · 20 ROUNDS' },
          { value: 30, label: 'STANDARD · 30 ROUNDS' },
          { value: 40, label: 'EPIC · 40 ROUNDS' },
        ],
        defaultValue: 30,
      },
      {
        key: 'economyVolatility',
        type: 'select',
        label: 'ECONOMY',
        description: 'Controls how sharply investments and world events move the market.',
        options: [
          { value: 'stable', label: 'STABLE' },
          { value: 'dynamic', label: 'DYNAMIC' },
          { value: 'wild', label: 'WILD' },
        ],
        defaultValue: 'dynamic',
      },
      {
        key: 'turnTimerSeconds',
        type: 'range',
        label: 'TURN TIMER',
        min: 20,
        max: 90,
        step: 5,
        defaultValue: 45,
        lowLabel: 'QUICK',
        highLabel: 'RELAXED',
        valueFormat: 'seconds',
      },
      {
        key: 'animationSpeed',
        type: 'range',
        label: 'ANIMATION PACE',
        min: 0.75,
        max: 1.5,
        step: 0.25,
        defaultValue: 1,
        lowLabel: 'CINEMATIC',
        highLabel: 'SNAPPY',
        valueFormat: 'multiplier',
      },
    ],
  },
};

export default manifest;
