import type { Character } from '../types';

export const CHARACTERS: Character[] = [
  {
    id: 'commando',
    name: 'COMMANDO',
    color: '#ff2e63',
    description: 'Frontline assault specialist. Balanced in all combat situations.',
    weaponType: 'burst_rifle',
    weaponName: 'BURST RIFLE',
    fireRate: 0.22,
    moveSpeedMultiplier: 1.0,
    bulletSpeedMultiplier: 1.0,
    damageMultiplier: 1.0,
    specialInfo: '3-Round Tactical Burst',
  },
  {
    id: 'scout',
    name: 'SCOUT',
    color: '#08d9d6',
    description: 'Recon expert. Light gear for rapid battlefield traversal.',
    weaponType: 'dual_smg',
    weaponName: 'DUAL SMGs',
    fireRate: 0.1,
    moveSpeedMultiplier: 1.2,
    bulletSpeedMultiplier: 1.1,
    damageMultiplier: 0.7,
    specialInfo: 'Rapid Fire & +20% Move Speed',
  },
  {
    id: 'heavy',
    name: 'HEAVY',
    color: '#2af598',
    description: 'Heavy weapons operator. Carries devastating firepower.',
    weaponType: 'heavy_cannon',
    weaponName: 'HEAVY CANNON',
    fireRate: 0.35,
    moveSpeedMultiplier: 0.85,
    bulletSpeedMultiplier: 0.9,
    damageMultiplier: 2.0,
    specialInfo: 'High Damage & Heavy Recoil',
  },
  {
    id: 'demolition',
    name: 'DEMOLITION',
    color: '#ffde7d',
    description: 'Explosives technician. Specializes in area destruction.',
    weaponType: 'grenade_launcher',
    weaponName: 'GRENADE LAUNCHER',
    fireRate: 0.4,
    moveSpeedMultiplier: 0.95,
    bulletSpeedMultiplier: 0.8,
    damageMultiplier: 1.5,
    specialInfo: 'Arcing Explosive Splash Damage',
  },
  {
    id: 'infiltrator',
    name: 'INFILTRATOR',
    color: '#7160e8',
    description: 'Covert operations. Silent but deadly on the field.',
    weaponType: 'plasma_beam',
    weaponName: 'PLASMA BEAM',
    fireRate: 0.28,
    moveSpeedMultiplier: 1.05,
    bulletSpeedMultiplier: 1.4,
    damageMultiplier: 1.2,
    specialInfo: 'High Velocity Piercing Beam',
  },
  {
    id: 'vanguard',
    name: 'VANGUARD',
    color: '#ff9f43',
    description: 'First-wave assault. Leads the charge into enemy territory.',
    weaponType: 'spread_shotgun',
    weaponName: 'SPREAD SHOTGUN',
    fireRate: 0.32,
    moveSpeedMultiplier: 1.0,
    bulletSpeedMultiplier: 0.95,
    damageMultiplier: 0.8,
    specialInfo: '5-Pellet Wide Cone Spread',
  },
];
