import { Graphics } from 'pixi.js';
import type { Blessing, RunPhase } from '../types';
import type { Hero } from '../entities/Hero';
import { PixelFont } from '../../turbo-rider/render/PixelFont';
import { ARENA_CONFIG } from '../config';

export class HUDManager {
  public render(g: Graphics, heroes: Hero[], title: string, enemiesLeft: number, phase: RunPhase, bossHp?: { name: string; hp: number; maxHp: number; phase: number }, blessing?: { choices: Blessing[]; votes: Map<number, number>; time: number }): void {
    const w = ARENA_CONFIG.width; const h = ARENA_CONFIG.height;
    if (phase === 'combat') { g.rect(w / 2 - 92, 3, 184, 18).fill({ color: 0x090611, alpha: .93 }); g.rect(w / 2 - 92, 3, 184, 18).stroke({ color: bossHp ? 0xf2c14e : 0x6ff7ff, width: 1, alpha: .75 }); PixelFont.drawText(g, bossHp ? `${bossHp.name}  P${bossHp.phase}` : `${title}  ${enemiesLeft} LEFT`, w / 2 - 84, 9, bossHp ? 0xf2c14e : 0xeaf6ff, 1); }
    if (bossHp) { const barX = w / 2 - 102; const pct = Math.max(0, bossHp.hp / bossHp.maxHp); g.rect(barX - 2, 24, 208, 10).fill({ color: 0x08040e, alpha: .94 }); g.rect(barX - 2, 24, 208, 10).stroke({ color: bossHp.phase === 3 ? 0xff526b : 0xf2c14e, width: 1 }); g.rect(barX, 27, 204 * pct, 4).fill({ color: bossHp.phase === 3 ? 0xe05263 : 0xb779f5 }); }
    const plateW = Math.floor((w - 10) / Math.max(heroes.length, 1)); heroes.forEach((hero, index) => { const x = 4 + index * plateW; const y = h - 31; const width = plateW - 4; g.rect(x, y, width, 27).fill({ color: 0x0a0712, alpha: .58 }); g.rect(x, y, width, 27).stroke({ color: hero.config.primaryColor, width: 1, alpha: .8 }); PixelFont.drawText(g, `P${hero.id} ${hero.config.name.substring(0, 4)}`, x + 4, y + 3, hero.config.primaryColor, 1); const barX = x + 36; const barW = Math.max(24, width - 72); g.rect(barX, y + 4, barW, 5).fill({ color: 0x30203c }); g.rect(barX, y + 4, barW * Math.max(0, hero.hp / hero.maxHp), 5).fill({ color: hero.isDowned ? 0xe05263 : 0xff526b }); g.rect(barX, y + 12, barW, 4).fill({ color: 0x30203c }); g.rect(barX, y + 12, barW * hero.mana / hero.maxMana, 4).fill({ color: 0x6ff7ff }); g.rect(barX, y + 20, barW, 3).fill({ color: 0x30203c }); g.rect(barX, y + 20, barW * hero.ultimate / 100, 3).fill({ color: 0xf2c14e }); const ready = hero.specialCooldownTimer <= 0 && hero.mana >= hero.config.specialManaCost; PixelFont.drawText(g, hero.isDowned ? 'DOWN' : hero.ultimate >= 100 ? 'ULT' : ready ? 'SKL' : `${Math.ceil(hero.specialCooldownTimer)}`, x + width - 25, y + 4, hero.ultimate >= 100 ? 0xf2c14e : ready ? 0x7de38a : 0xa48ba8, 1); if (hero.isDowned) PixelFont.drawText(g, 'REVIVE', x + width - 30, y + 16, 0xff526b, 1); });
    if (phase === 'room-intro') { g.rect(58, 92, 364, 72).fill({ color: 0x0a0712, alpha: .48 }); g.rect(58, 92, 364, 72).stroke({ color: 0x6ff7ff, width: 2, alpha: .8 }); PixelFont.drawText(g, title, Math.max(74, 240 - title.length * 6), 108, 0xf2c14e, 2); PixelFont.drawText(g, 'STEEL YOURSELVES', 174, 143, 0xeaf6ff, 1); }
    if (blessing && phase === 'blessing') { g.rect(18, 37, 444, 172).fill({ color: 0x0a0712, alpha: .9 }); g.rect(18, 37, 444, 172).stroke({ color: 0xf2c14e, width: 2 }); PixelFont.drawText(g, 'CHOOSE A PARTY BLESSING', 124, 49, 0xf2c14e, 1); blessing.choices.forEach((choice, index) => { const x = 29 + index * 145; const votes = [...blessing.votes.values()].filter(vote => vote === index).length; g.rect(x, 73, 132, 106).fill({ color: 0x1b1324, alpha: .52 }); g.rect(x, 73, 132, 106).stroke({ color: choice.color, width: 2 }); g.circle(x + 18, 94, 9).fill({ color: choice.color, alpha: .2 }); g.circle(x + 18, 94, 6).stroke({ color: choice.color, width: 2 }); PixelFont.drawText(g, choice.name, x + 34, 90, choice.color, 1); const words = choice.description.split(' '); const middle = Math.ceil(words.length / 2); PixelFont.drawText(g, words.slice(0, middle).join(' '), x + 8, 116, 0xeaf6ff, 1); PixelFont.drawText(g, words.slice(middle).join(' '), x + 8, 131, 0xeaf6ff, 1); PixelFont.drawText(g, `VOTES ${votes}`, x + 8, 158, votes ? 0x7de38a : 0xa48ba8, 1); }); PixelFont.drawText(g, `${Math.ceil(blessing.time)}S   LEFT RIGHT   ATTACK VOTE`, 119, 192, 0x6ff7ff, 1); }
  }
}
