export const PLATFORM_PHYSICS = {
  GRAVITY: 1200,
  JUMP_VELOCITY: -420,
  MOVE_SPEED: 180,
  WALL_SLIDE_SPEED: 70,
  SHADOW_DASH_SPEED: 380,
  SHADOW_DASH_DURATION: 0.25,
  SHADOW_DASH_COOLDOWN: 1.2,
  POGO_BOUNCE_VELOCITY: -350,
  NAIL_RECOIL_VELOCITY: 120,
};

export const COMBAT_STATS = {
  NAIL_DAMAGE: 25,
  MAX_SOUL: 100,
  SOUL_PER_HIT: 11,
  SPELL_SOUL_COST: 33,
  MASK_HP: 5,
};

export const CAVERN_CONFIG = {
  width: 960,
  height: 270,
  tileSize: 16,
};
